theme: jekyll-theme-cayman
title: Buddyfight! Málaga
description: Comunidad de Future Card Buddyfight! de Málaga (España)
baseurl: http://buddyfightmlg.opentheflag.com/
github:
  is_project_page: false
